### ISSUE TITLE
Script Command Error

### ISSUE THREAD

**Issue by BenOSanders** [elijahsawyers/autostack#13]
When I run "autostack-terminal" I get this:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/autostack-terminal", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/bensanders/repos/AutoStack/autostack/autostack-terminal", line 2, in <module>
    script -q -F /tmp/monitorPipe
NameError: name 'script' is not defined

**But** When I run the command manually ("script -q -F /tmp/monitorPipe") I get no error

**Comment by BenOSanders** [comment]
<img width="1280" alt="Screen Shot 2019-07-18 at 6 21 48 PM" src="https://user-images.githubusercontent.com/8213807/61498675-d1fad080-a989-11e9-9c53-d850e8defb91.png">
