### ISSUE TITLE
"raw_input" Name Error

### ISSUE THREAD

**Issue by BenOSanders** [elijahsawyers/autostack#14]
After AS runs, gives me an answer, then asks if I was satisfied I got this:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/autostack", line 11, in <module>
    load_entry_point('autostack==0.0.9', 'console_scripts', 'autostack')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/autostack/__main__.py", line 92, in main
    question_answered = raw_input()
NameError: name 'raw_input' is not defined

**Comment by BenOSanders** [comment]
<img width="1280" alt="Screen Shot 2019-07-18 at 6 21 48 PM" src="https://user-images.githubusercontent.com/8213807/61498649-b98ab600-a989-11e9-9a95-11a6bfa1bfce.png">

**Comment by BenOSanders** [comment]
`print('Did this answer your question? (Y/n): ', end='')`
Changed to
`question_answered = raw_input('Did this answer your question? (Y/n): ')`
