### ISSUE TITLE
No Module Found

### ISSUE THREAD

**Issue by BenOSanders** [elijahsawyers/autostack#15]
**Describe the Bug**
I installed autostack using "python setup.py install" and "pip3 install python". Both times I received this error when I ran the "autostack" command.

> Traceback (most recent call last):
>   File "/usr/local/bin/autostack", line 11, in <module>
>     load_entry_point('autostack==0.0.10', 'console_scripts', 'autostack')()
>   File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
>     return ep.load()
>   File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
>     return self.resolve()
>   File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
> ImportError: No module named autostack.__main__

**To Reproduce**
I have run this inside and out of venv, both yielding similar results.

**Expected Behavior**
"Listening on this terminal..." or something similar.

**Actual Behavior**
I received the error above or this:

> Traceback (most recent call last):
>   File "autostack", line 11, in <module>
>     load_entry_point('autostack==0.0.10', 'console_scripts', 'autostack')()
>   File "/Users/bensanders/repos/AutoStack/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/Users/bensanders/repos/AutoStack/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
>     return ep.load()
>   File "/Users/bensanders/repos/AutoStack/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
>     return self.resolve()
>   File "/Users/bensanders/repos/AutoStack/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
> ModuleNotFoundError: No module named 'autostack'
> 

**Device Information (please complete the following information):**
 - OS: Mac OS
 - OS Version: 10.15.5
 - Python Version: 3.7.4

**Additional Context**
None.

**Comment by BenOSanders** [comment]
https://stackoverflow.com/questions/16981921/relative-imports-in-python-3 might be helpful

**Comment by BenOSanders** [comment]
So this only occurs when I run "autostack"
When I run "python3 autostack" I'm getting it to work, but I did change line 13 of __main__.py from
`from .web_scraper.stack_overflow_scraper import (`
to
`from web_scraper.stack_overflow_scraper import (`
